// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OficioMVC.Models;

namespace OficioMVC.Migrations
{
    [DbContext(typeof(OficioMVCContext))]
    [Migration("20200307021215_teste")]
    partial class teste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OficioMVC.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Ano");

                    b.Property<string>("Assunto");

                    b.Property<string>("CaminhoArq");

                    b.Property<DateTime>("DataEnvio");

                    b.Property<string>("Observacoes");

                    b.Property<int>("Siga_profs_id");

                    b.Property<int?>("UsuarioID");

                    b.HasKey( "Id", "Ano");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Documento");
                });

            modelBuilder.Entity("OficioMVC.Models.Siga_profs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ativo");

                    b.Property<int>("dpto");

                    b.Property<string>("user_login");

                    b.Property<string>("user_nicename");

                    b.Property<string>("user_pass");

                    b.HasKey("ID");

                    b.ToTable("Siga_profs");
                });

            modelBuilder.Entity("OficioMVC.Models.Documento", b =>
                {
                    b.HasOne("OficioMVC.Models.Siga_profs", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID");
                });
#pragma warning restore 612, 618
        }
    }
}
